Repository openpathsampling/openpathsampling, pull requests merged in 2018-10, with the labels that each got.

#798 Updates to Examples
  examples/alanine_dipeptide_tps/AD_tps_1_trajectory.ipynb
  examples/alanine_dipeptide_tps/AD_tps_3a_analysis_flex.ipynb
  examples/alanine_dipeptide_tps/AD_tps_3b_analysis_fixed.ipynb
  examples/alanine_dipeptide_tps/AD_tps_4_advanced.ipynb
  examples/misc/custom_strategy_repex_shoot_repex.ipynb
  examples/toy_model_mistis/toy_mistis_1_setup_run.ipynb
  examples/toy_model_mistis/toy_mistis_2_flux.ipynb
  examples/toy_model_mistis/toy_mistis_3_analysis.ipynb
  openpathsampling/engines/openmm/engine.py
Labels: misc PR

#768 Attempt to fix for old openmmtools as well as new
  openpathsampling/engines/openmm/engine.py
Labels: bugfix, upstream changed

#790 PEP8 cleanup after #788
  openpathsampling/high_level/move_strategy.py
  openpathsampling/shooting.py
  openpathsampling/tests/test_movestrategy.py
  openpathsampling/tests/test_shooting.py
Labels: misc PR

#799 Load file with reduced box vectors
  examples/tests/test_netcdfplus.ipynb
  examples/tests/test_openmm_integration.ipynb
  examples/tests/test_pyemma.ipynb
  examples/tests/test_snapshot.ipynb
  examples/toy_model_mistis/toy_mistis_1_setup_run.ipynb
  openpathsampling/engines/openmm/tools.py
  openpathsampling/tests/test_data/reduce_box_vects/dna.gro
  openpathsampling/tests/test_data/reduce_box_vects/dna.trr
  openpathsampling/tests/test_openmm_tools.py
Labels: feature

#791 added examples to constrained move
  examples/toy_model_mstis/constrainedshooting_mstis.ipynb
  examples/toy_model_mstis/constrainedshooting_mstis_2.ipynb
Labels: feature
