Repository openpathsampling/openpathsampling, pull requests merged in 2018-06, with the labels that each got.

#772 Minor bugs/Implementation improvements
  openpathsampling/ensemble.py
  openpathsampling/pathmover.py
  openpathsampling/tests/test_ensemble.py
  openpathsampling/tests/test_volume.py
  openpathsampling/volume.py
Labels: bugfix

#754 Split pathsimulator.py
  openpathsampling/__init__.py
  openpathsampling/pathsimulator.py
  openpathsampling/pathsimulators/__init__.py
  openpathsampling/pathsimulators/bootstrap_init_conds.py
  openpathsampling/pathsimulators/direct_md.py
  openpathsampling/pathsimulators/path_sampling.py
  openpathsampling/pathsimulators/path_simulator.py
  openpathsampling/pathsimulators/shoot_snapshots.py
  openpathsampling/storage/stores/mcstep.py
  openpathsampling/storage/stores/pathsimulator.py
  openpathsampling/tests/test_pathsimulator.py
  setup.py
Labels: misc PR

#760 Pin conda version in `miniconda_install`
  .travis.yml
  devtools/ci/miniconda_install.sh
Labels: misc PR

#781 Fix pandas deprecation warning : replace df.as_matrix() with df.values
  examples/misc/custom_strategy_repex_shoot_repex.ipynb
  examples/toy_model_mstis/toy_mstis_3_analysis.ipynb
  openpathsampling/numerics/wham.py
  openpathsampling/tests/test_channel_analysis.py
  openpathsampling/tests/test_pathsimulator.py
  openpathsampling/tests/test_wham.py
Labels: misc PR

#783 Only keep existing value stores in attribute_list
  openpathsampling/netcdfplus/netcdfplus.py
Labels: bugfix

#782 omit using rejected paths in correlation visualization
  openpathsampling/visualize.py
Labels: bugfix

#785 Fix push-docs-to-s3 for pip 10
  devtools/ci/after_sucess.sh
  devtools/ci/push-docs-to-s3.py
  docs/data_objects.rst
  docs/pathsimulator.rst
  docs/topics/data_objects.rst
Labels: docs, misc PR
