Repository openpathsampling/openpathsampling, pull requests merged in 2019-11, with the labels that each got.

#867 Reduce requirements
  .travis.yml
  devtools/minimal.txt
  devtools/minimal_testing.txt
  docs/install.rst
  openpathsampling/collectivevariable.py
  openpathsampling/engines/dynamics_engine.py
  openpathsampling/engines/features/coordinates.py
  openpathsampling/engines/features/shared.py
  openpathsampling/engines/features/statics.py
  openpathsampling/engines/openmm/__init__.py
  openpathsampling/engines/openmm/tools.py
  openpathsampling/engines/trajectory.py
  openpathsampling/integration_tools.py
  openpathsampling/netcdfplus/dictify.py
  openpathsampling/netcdfplus/netcdfplus.py
  openpathsampling/step_visualizer_2D.py
  openpathsampling/tests/__init__.py
  openpathsampling/tests/test_attribute.py
  openpathsampling/tests/test_collectivevariable.py
  openpathsampling/tests/test_ensemble.py
  openpathsampling/tests/test_features.py
  openpathsampling/tests/test_helpers.py
  openpathsampling/tests/test_mdtraj_support.py
  openpathsampling/tests/test_openmm_engine.py
  openpathsampling/tests/test_openmm_snapshot.py
  openpathsampling/tests/test_openmm_tools.py
  openpathsampling/tests/test_shared.py
  openpathsampling/tests/test_snapshot.py
  openpathsampling/tests/test_snapshot_modifier.py
  openpathsampling/tests/test_storage.py
  openpathsampling/tests/test_volume.py
  setup.py
Labels: misc PR

#874 Add information to MinusMove change.details
  openpathsampling/pathmover.py
  openpathsampling/tests/test_pathmover.py
Labels: enhancement

#875 Path density: Bresenham interpolation
  examples/misc/tutorial_path_histogram.ipynb
  openpathsampling/analysis/path_histogram.py
  openpathsampling/tests/test_path_histogram.py
Labels: feature

#877 Fix coveralls parallel build issues
  .travis.yml
  devtools/ci/pytests.sh
  devtools/testing_requirements.txt
Labels: misc PR

#880 Some toy engine reprs
  openpathsampling/engines/toy/pes.py
Labels: misc PR

#881 fix docstring Deprecation warning
  openpathsampling/engines/toy/pes.py
Labels: docs, misc PR
