Repository openpathsampling/openpathsampling, pull requests merged in 2020-10, with the labels that each got.

#935 Improve CV storage error message about missing templates
  openpathsampling/netcdfplus/stores/attribute.py
Labels: misc PR

#933 Internalized snapshots; random filenames for external snapshots
  openpathsampling/engines/external_engine.py
  openpathsampling/engines/external_snapshots/__init__.py
  openpathsampling/engines/external_snapshots/snapshot.py
  openpathsampling/engines/gromacs/__init__.py
  openpathsampling/engines/gromacs/engine.py
  openpathsampling/engines/snapshot.py
  openpathsampling/tests/test_external_engine.py
  openpathsampling/tests/test_external_snapshots.py
  openpathsampling/tests/test_gromacs_engine.py
Labels: enhancement

#928 SimStore: New storage subsystem (part 1)
  .coveragerc
  devtools/ci/create_conda_meta.py
  devtools/ci/pytests.sh
  devtools/conda_install_reqs.sh
  devtools/experimental_reqs.txt
  openpathsampling/engines/features/base.py
  openpathsampling/engines/features/coordinates.py
  openpathsampling/engines/features/engine.py
  openpathsampling/engines/features/statics.py
  openpathsampling/engines/features/velocities.py
  openpathsampling/engines/toy/pes.py
  openpathsampling/engines/trajectory.py
  openpathsampling/experimental/README.md
  openpathsampling/experimental/__init__.py
  openpathsampling/experimental/simstore/__init__.py
  openpathsampling/experimental/simstore/backend.py
  openpathsampling/experimental/simstore/class_info.py
  openpathsampling/experimental/simstore/class_lookup.py
  openpathsampling/experimental/simstore/custom_json.py
  openpathsampling/experimental/simstore/dict_serialization_helpers.py
  openpathsampling/experimental/simstore/my_types.py
  openpathsampling/experimental/simstore/serialization.py
  openpathsampling/experimental/simstore/serialization_helpers.py
  openpathsampling/experimental/simstore/sql_backend.py
  openpathsampling/experimental/simstore/storage.py
  openpathsampling/experimental/simstore/test_backend.py
  openpathsampling/experimental/simstore/test_class_info.py
  openpathsampling/experimental/simstore/test_custom_json.py
  openpathsampling/experimental/simstore/test_dict_serialization_helpers.py
  openpathsampling/experimental/simstore/test_serialization.py
  openpathsampling/experimental/simstore/test_serialization_helpers.py
  openpathsampling/experimental/simstore/test_sql_backend.py
  openpathsampling/experimental/simstore/test_storage.py
  openpathsampling/experimental/simstore/test_tools.py
  openpathsampling/experimental/simstore/test_utils.py
  openpathsampling/experimental/simstore/tools.py
  openpathsampling/experimental/storage/__init__.py
  openpathsampling/experimental/storage/mdtraj_json.py
  openpathsampling/experimental/storage/monkey_patches.py
  openpathsampling/experimental/storage/ops_storage.py
  openpathsampling/experimental/storage/snapshots.py
  openpathsampling/experimental/storage/test_mdtraj_json.py
  openpathsampling/experimental/storage/test_snapshots.py
  openpathsampling/high_level/interface_set.py
  openpathsampling/movechange.py
  openpathsampling/pathsimulators/path_sampling.py
  openpathsampling/sample.py
  pytest.ini
Labels: experimental

#936 Fix collections.abc DeprecationWarning in sample.py
  openpathsampling/sample.py
Labels: misc PR, upstream changed

#938 OpenMM instantaneous temp should work if positions not set
  openpathsampling/engines/openmm/features/instantaneous_temperature.py
  openpathsampling/tests/test_openmm_snapshot.py
Labels: bugfix

#939 Minor improvements on CLI docs
  docs/cli.rst
Labels: docs, misc PR

#929 SimStore part 2: Storable functions (and more)
  openpathsampling/engines/external_snapshots/features/file_info.py
  openpathsampling/experimental/simstore/__init__.py
  openpathsampling/experimental/simstore/callable_codec.py
  openpathsampling/experimental/simstore/class_info.py
  openpathsampling/experimental/simstore/custom_json.py
  openpathsampling/experimental/simstore/memory_backend.py
  openpathsampling/experimental/simstore/serialization.py
  openpathsampling/experimental/simstore/serialization_helpers.py
  openpathsampling/experimental/simstore/sql_backend.py
  openpathsampling/experimental/simstore/storable_functions.py
  openpathsampling/experimental/simstore/storage.py
  openpathsampling/experimental/simstore/test_callable_codec.py
  openpathsampling/experimental/simstore/test_class_info.py
  openpathsampling/experimental/simstore/test_serialization_helpers.py
  openpathsampling/experimental/simstore/test_storable_function.py
  openpathsampling/experimental/storage/collective_variables.py
  openpathsampling/experimental/storage/ops_storage.py
  openpathsampling/experimental/storage/snapshots_table.py
  openpathsampling/experimental/storage/test_collective_variables.py
  openpathsampling/experimental/storage/test_snapshot_integrations.py
  openpathsampling/experimental/storage/test_snapshots_table.py
  openpathsampling/high_level/interface_set.py
  openpathsampling/high_level/transition.py
Labels: experimental
