Repository openpathsampling/openpathsampling, pull requests merged in 2020-02, with the labels that each got.

#898 Fix pandas Deprepaction and Future Warnings
  openpathsampling/numerics/wham.py
  openpathsampling/tests/test_resampling_statistics.py
  openpathsampling/tests/test_tis_analysis.py
Labels: misc PR, upstream changed

#900 Fix missing newline in the VisitAllStatesEnsemble
  openpathsampling/ensembles/visit_all_states.py
  openpathsampling/tests/test_visit_all_states.py
Labels: misc PR

#895 Progress indicators for TIS analysis
  examples/toy_model_mstis/toy_mstis_A3_new_analysis.ipynb
  openpathsampling/analysis/tis/core.py
  openpathsampling/analysis/tis/flux.py
  openpathsampling/analysis/tis/standard_analysis.py
  openpathsampling/progress.py
  openpathsampling/tests/test_tis_analysis.py
Labels: enhancement

#902 Progress indicators for path density; move summary
  openpathsampling/analysis/path_histogram.py
  openpathsampling/high_level/move_scheme.py
  openpathsampling/tests/test_movescheme.py
  openpathsampling/tests/test_path_histogram.py
Labels: enhancement

#901 Add GromacsEngine to docs
  docs/engines/gromacs.rst
  docs/examples/miscellaneous/gromacs.rst
  docs/videos.rst
  openpathsampling/analysis/channel_analysis.py
  openpathsampling/engines/dynamics_engine.py
  openpathsampling/engines/external_snapshots/snapshot.py
  openpathsampling/engines/gromacs/engine.py
  openpathsampling/engines/snapshot.py
  openpathsampling/volume.py
Labels: docs, misc PR

#778 fixed caching_mode='unlimited'
  openpathsampling/storage/storage.py
Labels: bugfix

#725 Fix Shooting Point Analysis
  openpathsampling/analysis/shooting_point_analysis.py
  openpathsampling/tests/test_shooting_point_analysis.py
Labels: bugfix
