Repository openpathsampling/openpathsampling, pull requests merged in 2020-12, with the labels that each got.

#947 SimStore: Type identification
  openpathsampling/experimental/simstore/sql_backend.py
  openpathsampling/experimental/simstore/storable_functions.py
  openpathsampling/experimental/simstore/storage.py
  openpathsampling/experimental/simstore/test_storable_function.py
  openpathsampling/experimental/simstore/test_type_ident.py
  openpathsampling/experimental/simstore/type_ident.py
  openpathsampling/experimental/storage/collective_variables.py
  openpathsampling/experimental/storage/test_collective_variables.py
  openpathsampling/high_level/interface_set.py
Labels: experimental

#949 SimStore: Support for OpenMM snapshots
  openpathsampling/engines/features/kinetics.py
  openpathsampling/engines/features/shared.py
  openpathsampling/engines/features/statics.py
  openpathsampling/engines/openmm/snapshot.py
  openpathsampling/engines/openmm/tools.py
  openpathsampling/experimental/simstore/attribute_handlers.py
  openpathsampling/experimental/simstore/class_info.py
  openpathsampling/experimental/simstore/class_lookup.py
  openpathsampling/experimental/simstore/custom_json.py
  openpathsampling/experimental/simstore/proxy.py
  openpathsampling/experimental/simstore/serialization.py
  openpathsampling/experimental/simstore/serialization_helpers.py
  openpathsampling/experimental/simstore/sql_backend.py
  openpathsampling/experimental/simstore/storable_functions.py
  openpathsampling/experimental/simstore/storage.py
  openpathsampling/experimental/simstore/test_attribute_handlers.py
  openpathsampling/experimental/simstore/test_class_info.py
  openpathsampling/experimental/simstore/test_serialization.py
  openpathsampling/experimental/simstore/test_storable_function.py
  openpathsampling/experimental/simstore/test_tags_table.py
  openpathsampling/experimental/simstore/uuids.py
  openpathsampling/experimental/storage/monkey_patches.py
  openpathsampling/experimental/storage/ops_storage.py
  openpathsampling/experimental/storage/simtk_unit.py
  openpathsampling/experimental/storage/snapshots.py
  openpathsampling/experimental/storage/test_snapshot_integrations.py
  openpathsampling/high_level/move_scheme.py
Labels: experimental

#950 SimStore: Simplify OPS Storage constructor
  openpathsampling/experimental/storage/ops_storage.py
Labels: experimental

#923 fix numpy 1.19 DeprecationWarning: tostring()
  openpathsampling/analysis/shooting_point_analysis.py
  openpathsampling/tests/test_network.py
  openpathsampling/tests/test_pathsimulator.py
  openpathsampling/tests/test_shooting_point_analysis.py
Labels: misc PR, upstream changed

#913 Fix: OPS hangs when external engine errors/exits unexpectedly
  openpathsampling/engines/dynamics_engine.py
  openpathsampling/engines/external_engine.py
  openpathsampling/engines/gromacs/engine.py
  openpathsampling/engines/toy/__init__.py
  openpathsampling/engines/toy/pes.py
Labels: bugfix

#951 Revert c2d47f0
  openpathsampling/engines/toy/__init__.py
  openpathsampling/engines/toy/pes.py
Labels: misc PR

#924 Reactive flux (updated PR)
  examples/misc/reactive_flux.ipynb
  openpathsampling/__init__.py
  openpathsampling/analysis/reactive_flux_analysis.py
  openpathsampling/movechange.py
  openpathsampling/pathmover.py
  openpathsampling/pathsimulators/__init__.py
  openpathsampling/pathsimulators/reactive_flux.py
  openpathsampling/tests/test_pathsimulator.py
  openpathsampling/tests/test_reactive_flux_analysis.py
Labels: feature

#954 fix omt is None error in test suite
  openpathsampling/tests/test_features.py
Labels: misc PR

#953 Remove things deprecated for 2.0
  openpathsampling/__init__.py
  openpathsampling/collectivevariable.py
  openpathsampling/deprecations.py
  openpathsampling/engines/openmm/engine.py
  openpathsampling/high_level/interface_set.py
  openpathsampling/high_level/network.py
  openpathsampling/pathmover.py
  openpathsampling/tests/test_api.py
Labels: 2.0

#958 Remove nose from test_helpers
  openpathsampling/tests/test_helpers.py
Labels: misc PR

#957 Fix so SimStore tests pass without simtk.unit
  openpathsampling/experimental/simstore/test_custom_json.py
  openpathsampling/experimental/storage/ops_storage.py
  openpathsampling/experimental/storage/test_collective_variables.py
  setup.cfg
Labels: misc PR
