Repository openpathsampling/openpathsampling, pull requests merged in 2021-04, with the labels that each got.

#999 make test less flaky
  openpathsampling/tests/test_shooting.py
Labels: misc PR

#1002 Fix SimStore NumPy deprecations
  openpathsampling/experimental/simstore/attribute_handlers.py
  openpathsampling/experimental/simstore/custom_json.py
Labels: misc PR, upstream changed

#993 Add Python 3.8, 3.9 to testing matrix
  .github/workflows/tests.yml
  codecov.yml
  devtools/ci/miniconda_install.sh
  examples/ipynbtests.sh
  examples/misc/tutorial_storage.ipynb
  examples/prep_example_data.py
  setup.cfg
Labels: misc PR

#998 Add global random number generator; support in shooting pt selectors and pathmovers
  openpathsampling/__init__.py
  openpathsampling/pathmover.py
  openpathsampling/pathmovers/spring_shooting.py
  openpathsampling/random.py
  openpathsampling/sample.py
  openpathsampling/shooting.py
  openpathsampling/tests/test_pathmover.py
  openpathsampling/tests/test_random.py
Labels: enhancement

#1003 Prevent netcdfplus from trying to load netcdfplus CVs as SimStore CVs
  openpathsampling/netcdfplus/base.py
Labels: bugfix, experimental

#1004 SimStore: Make storable function modes customizable
  openpathsampling/experimental/simstore/storable_functions.py
  openpathsampling/experimental/simstore/test_storable_function.py
Labels: experimental

#1009 Ignore more flaky PyEMMA on Python 2.7
  examples/tests/test_pyemma.ipynb
Labels: misc PR

#1012 Move MDTrajTopology
  openpathsampling/collectivevariable.py
  openpathsampling/collectivevariables/plumed_wrapper.py
  openpathsampling/deprecations.py
  openpathsampling/engines/__init__.py
  openpathsampling/engines/gromacs/engine.py
  openpathsampling/engines/openmm/engine.py
  openpathsampling/engines/openmm/tools.py
  openpathsampling/engines/openmm/topology.py
  openpathsampling/engines/topology.py
  openpathsampling/experimental/storage/test_collective_variables.py
Labels: misc PR

#1014 Fix backward compatiblity for MDTrajTopology
  openpathsampling/engines/openmm/__init__.py
Labels: misc PR
