Repository openpathsampling/openpathsampling, pull requests merged in 2021-07, with the labels that each got.

#911 "Hooks" for PathSampling
  openpathsampling/beta/hooks.py
  openpathsampling/pathsimulators/path_sampling.py
  openpathsampling/step_visualizer_2D.py
  openpathsampling/tests/pathsimulators/test_hooks.py
Labels: feature

#914 Gracious kill hook
  openpathsampling/beta/hooks.py
  openpathsampling/tests/pathsimulators/test_hooks.py
Labels: feature

#1034 Fix bug in live visualizer setup with implicit hooks
  openpathsampling/pathsimulators/path_sampling.py
  openpathsampling/tests/pathsimulators/test_hooks.py
Labels: bugfix

#1036 Fix DataFrame.sort_index future warning
  openpathsampling/numerics/lookup_function.py
Labels: misc PR, upstream changed

#1037 Fix OpenMM engine docs on n_frames_max
  openpathsampling/engines/openmm/engine.py
Labels: docs, misc PR

#1035 Fix bug with SimStore CVs storing NumPy arrays
  openpathsampling/deprecations.py
  openpathsampling/experimental/simstore/class_info.py
  openpathsampling/experimental/simstore/memory_backend.py
  openpathsampling/experimental/simstore/regressions/README.md
  openpathsampling/experimental/simstore/regressions/test_numpy_sfrs.py
  openpathsampling/experimental/simstore/serialization.py
  openpathsampling/experimental/simstore/sql_backend.py
  openpathsampling/experimental/simstore/storable_functions.py
  openpathsampling/experimental/simstore/storage.py
  openpathsampling/experimental/simstore/test_sql_backend.py
  openpathsampling/experimental/simstore/test_storable_function.py
Labels: bugfix, experimental
