Repository openpathsampling/openpathsampling, pull requests merged in 2021-08, with the labels that each got.

#1043 Update CI for OPS 2.0
  .github/workflows/test-2.0.yml
  examples/ipynbtests.sh
Labels: misc PR, 2.0

#1046 Prevent errors in ShootingPointAnalysis with invalid (e.g., max length) trajectories
  openpathsampling/analysis/shooting_point_analysis.py
  openpathsampling/tests/test_shooting_point_analysis.py
Labels: bugfix

#1047 Change ShootingPointAnalysisError to an Exception
  openpathsampling/analysis/shooting_point_analysis.py
Labels: misc PR, 2.0

#1051 Fixes for OpenMM 7.6 RC
  .github/workflows/check-openmm-rc.yml
  openpathsampling/__init__.py
  openpathsampling/engines/features/shared.py
  openpathsampling/engines/features/statics.py
  openpathsampling/engines/gromacs/__init__.py
  openpathsampling/engines/gromacs/engine.py
  openpathsampling/engines/openmm/__init__.py
  openpathsampling/engines/openmm/engine.py
  openpathsampling/engines/openmm/features/__init__.py
  openpathsampling/engines/openmm/features/instantaneous_temperature.py
  openpathsampling/engines/openmm/features/masses.py
  openpathsampling/engines/openmm/features/traj_quantities.py
  openpathsampling/engines/openmm/tools.py
  openpathsampling/engines/topology.py
  openpathsampling/experimental/storage/simtk_unit.py
  openpathsampling/experimental/storage/test_simtk_unit.py
  openpathsampling/integration_tools.py
  openpathsampling/netcdfplus/dictify.py
  openpathsampling/netcdfplus/netcdfplus.py
  openpathsampling/snapshot_modifier.py
  openpathsampling/tests/test_helpers.py
  openpathsampling/tests/test_integration_tools.py
  openpathsampling/tests/test_openmm_engine.py
  openpathsampling/tests/test_openmm_tools.py
  openpathsampling/tests/test_snapshot_modifier.py
  openpathsampling/tests/test_volume.py
  openpathsampling/volume.py
Labels: misc PR, upstream changed

#1058 Remove engine binary after tests
  openpathsampling/tests/test_external_engine.py
Labels: misc PR
