Repository openpathsampling/openpathsampling, pull requests merged in 2021-12, with the labels that each got.

#1091 Guard against openmm import warnings (including those from OpenMMTools)
  examples/tests/test_openmm_integration.ipynb
Labels: misc PR

#1068 New analysis testing utilities
  openpathsampling/tests/analysis/__init__.py
  openpathsampling/tests/analysis/conftest.py
  openpathsampling/tests/analysis/utils/__init__.py
  openpathsampling/tests/analysis/utils/fixture_classes.py
  openpathsampling/tests/analysis/utils/mock_movers.py
  openpathsampling/tests/analysis/utils/test_fixture_classes.py
  openpathsampling/tests/analysis/utils/test_mock_movers.py
Labels: enhancement

#1092 Actually check for CVDefinedVolume.lambda_max == "inf"
  openpathsampling/tests/test_volume.py
  openpathsampling/volume.py
Labels: bugfix

#1096 make a missed string into a rawstring
  openpathsampling/engines/toy/pes.py
Labels: misc PR
