Repository openpathsampling/openpathsampling, pull requests merged in 2021-02, with the labels that each got.

#977 kill off getslice
  .github/workflows/tests.yml
  openpathsampling/engines/trajectory.py
  openpathsampling/ensemble.py
  openpathsampling/netcdfplus/netcdfplus.py
Labels: 2.0, drop-py2

#980 Add codecov.yml
  .github/workflows/tests.yml
  codecov.yml
Labels: misc PR

#981 Remove some Py2-specific code
  openpathsampling/analysis/shooting_point_analysis.py
  openpathsampling/collectivevariable.py
  openpathsampling/deprecations.py
  openpathsampling/engines/dynamics_engine.py
  openpathsampling/ensemble.py
  openpathsampling/sample.py
Labels: 2.0, drop-py2

#972 Fix problem with Histogram.bin_range not getting set
  openpathsampling/numerics/histogram.py
  openpathsampling/tests/test_histogram.py
Labels: bugfix

#983 Fix MISTIS minus ensemble not forbidding other states
  openpathsampling/high_level/network.py
  openpathsampling/tests/test_network.py
Labels: bugfix
