Repository openpathsampling/openpathsampling, pull requests merged in 2021-03, with the labels that each got.

#985 Integration tests for SimStore StorableFunctions
  openpathsampling/experimental/simstore/__init__.py
  openpathsampling/experimental/simstore/memory_backend.py
  openpathsampling/experimental/simstore/sql_backend.py
  openpathsampling/experimental/simstore/storable_functions.py
  openpathsampling/experimental/simstore/storage.py
  openpathsampling/experimental/simstore/test_storable_function.py
  openpathsampling/experimental/simstore/test_storable_function_integration.py
Labels: bugfix, experimental

#988 Fix problem with repeated ensemble names in MISTIS
  openpathsampling/high_level/network.py
  openpathsampling/high_level/transition.py
Labels: bugfix

#850 Add spring shooting to OPS core
  examples/misc/spring_shooting_example.ipynb
  openpathsampling/pathmovers/__init__.py
  openpathsampling/pathmovers/move_schemes.py
  openpathsampling/pathmovers/spring_shooting.py
  openpathsampling/tests/test_helpers.py
  openpathsampling/tests/test_spring_shooting.py
Labels: feature

#987 Switch notebook tests to nbval
  examples/ipynbtests.sh
  examples/tests/test_cv.ipynb
  examples/tests/test_netcdfplus.ipynb
  examples/tests/test_openmm_integration.ipynb
  examples/tests/test_pyemma.ipynb
  examples/tests/test_snapshot.ipynb
  examples/toy_model_mistis/toy_mistis_1_setup_run.ipynb
  examples/toy_model_mistis/toy_mistis_3_analysis.ipynb
  examples/toy_model_mstis/toy_mstis_2_run.ipynb
  examples/toy_model_mstis/toy_mstis_3_analysis.ipynb
  setup.cfg
Labels: misc PR

#991 Add threshold to codecov.yml
  codecov.yml
Labels: misc PR

#990 SimStore: Periodic CVs
  openpathsampling/experimental/simstore/storable_functions.py
  openpathsampling/experimental/simstore/test_storable_function.py
  openpathsampling/experimental/storage/collective_variables.py
Labels: experimental

#995 SimStore storage.cvs should only be CVs
  openpathsampling/experimental/storage/ops_storage.py
Labels: bugfix, experimental

#979 Move n_dofs to engine; add engine.has_constraints()
  openpathsampling/engines/openmm/engine.py
  openpathsampling/engines/openmm/features/instantaneous_temperature.py
  openpathsampling/engines/openmm/tools.py
  openpathsampling/engines/toy/engine.py
  openpathsampling/engines/toy/features/instantaneous_temperature.py
  openpathsampling/snapshot_modifier.py
  openpathsampling/tests/test_openmm_engine.py
  openpathsampling/tests/test_snapshot_modifier.py
  openpathsampling/tests/test_toy_dynamics.py
Labels: enhancement
