Repository openpathsampling/openpathsampling, pull requests merged in 2022-01, with the labels that each got.

#1066 Clear old ExternalMDSnapshots during `iter_generate`
  openpathsampling/engines/dynamics_engine.py
  openpathsampling/engines/external_snapshots/snapshot.py
  openpathsampling/engines/gromacs/engine.py
  openpathsampling/tests/test_dynamicsengine.py
  openpathsampling/tests/test_gromacs_engine.py
Labels: enhancement

#1100 Move check-openmm-rc off of main branch
  .github/workflows/check-openmm-rc.yml
Labels: misc PR

#1102 Add FutureWarning for default filesetter external engines
  openpathsampling/deprecations.py
  openpathsampling/engines/external_engine.py
  openpathsampling/tests/test_external_engine.py
Labels: misc PR, Deprecations
